import { Flex, Heading, Image, Box } from "@chakra-ui/react";

export default function Clientes() {
  return (
    <>
      <Flex
        w="100%"
        bg="linear-gradient(20deg, rgba(50,100,255,1) 38%, rgba(0,180,232,1) 100%)"
        flexDir="column"
        align="center"
      >
        <Heading marginTop="2rem" fontFamily={"fantasy"} color="white">
          Alguns de nossos Clientes
        </Heading>
        <Flex justify="center" w="75%" flexWrap="wrap" h="15rem" margin="5rem">
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            boxShadow="dark-lg"
            margin="5px"
          >
            <Image src="asia_logo.png" alt="asia logo" h="100px" w="150px" />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image src="brado_logo.png" alt="asia logo" h="100px" w="150px" />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image src="cargil_logo.png" alt="asia logo" h="100px" w="150px" />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginTop="2px"
              src="santos_logo.png"
              alt="santos logo"
              h="95px"
              w="145px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="cofco_logo.png"
              alt="cofco logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="sepetiba_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="sungrow_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="escoporto_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="super_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="grupo_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="incatep_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="tcp_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="tecon_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="teconSuape_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="termobras_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="wilson_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="zarate_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
          <Box
            width="150px"
            h="100px"
            bg="white"
            rounded="md"
            margin="5px"
            boxShadow="dark-lg"
          >
            <Image
              marginLeft="5px"
              src="mrs_logo.png"
              alt="asia logo"
              h="95px"
              w="140px"
            />
          </Box>
        </Flex>
      </Flex>
    </>
  );
}
